### ISSUE TITLE
EverMemo是怎么在ActionBar上实现popup menu的？

### ISSUE THREAD

**Issue by puma007** [daimajia/EverMemo#16]
最近手机装了EverMemo，不知道你在ActionBar上是如何实现popup menu的？看了EverMemo的源码，没有找到实现方法啊？谢谢！

**Comment by daimajia** [comment]
是通过menu菜单实现的，Android的ActionBar兼容库提供支持ActionBar。
https://github.com/daimajia/EverMemo/blob/ActionBarMemo/res/menu/start.xml

**Comment by puma007** [comment]
非常感谢！
