### ISSUE TITLE
引用项目问题，新手

### ISSUE THREAD

**Issue by sos303sos** [daimajia/EverMemo#17]
我下载项目后，project.properties文件中的
android.library.reference.1=../ExGridView
android.library.reference.2=../Evernote

这两个项目如何作为library引用进来，
1.Evernote的sdk我能找到，但是不会引用进来
2.ExGridView这个根本就不知道在哪？

**Comment by daimajia** [comment]
这两个是第三方库，现在还没有正式开源 所以请稍等一段时间。

**Comment by daimajia** [comment]
你好，EverMemo正式开源了，可以编译啦~
