### ISSUE TITLE
About the Gradle Compile 

### ISSUE THREAD

**Issue by LilyBlooper** [daimajia/EverMemo#19]
### Hi there!

I've downloaded the src code zip.And I already install the gradle and set the environment 
variables .Gradle needs sdk build-tools and support-library to compile..
At last,it seems that I succeed.Just like the snap below:
![image](https://f.cloud.github.com/assets/7007552/2480100/2e5c1f20-b0af-11e3-9c8e-2a20279f8950.png)
And now,in the root directory.A build directory is created.
![image](https://f.cloud.github.com/assets/7007552/2480103/530b71cc-b0af-11e3-8f16-7dfb6de130c9.png)

I wanna to import the src into my AndroidADT (Eclipse) workspace and look into the source code .However,the structure does't seems to be a  typical Android Project.

**So,what should I do to see the source code just like any other proect in the github.
Those projects only need to be decompressed and import.Just like this:**

![image](https://f.cloud.github.com/assets/7007552/2480121/f7b73256-b0af-11e3-8cb0-c305618c9565.png)

**Comment by daimajia** [comment]
This is an Android Studio project , so if you wanna to import it into Eclipse.

try this: Run : `android update project -p .` in root directory.

You can see more here: http://developer.android.com/tools/projects/projects-cmdline.html

and also you should update two libraries project: run in root directory of two libraries project  `android update lib-project -p .`

have a try, if there is some problems, feel free to connect me.

**Comment by daimajia** [comment]
If you use Android studio , it will be extremely easy to import.

**Comment by LilyBlooper** [comment]
Much Thanks! I'll try it !

**Comment by LilyBlooper** [comment]
Very sadly,it seems impossible to import an Android Studion Project into Eclipse(with ADT),as the 
answers in StackOverflow . 

http://stackoverflow.com/questions/16745793/how-do-you-open-an-android-studio-project-in-eclipse

or 

http://stackoverflow.com/questions/17481915/how-to-import-android-studio-project-in-eclipse

so,maybe either I use the Android Studio,or I can copy the files manually.

The instructions from google is not aim to transfer projects from Android Studio to Eclipse .

Thanks anyway!

**Comment by daimajia** [comment]
It should be possible, maybe a little complex.

Anyway , welcome to use Android Studio .
